GET http://localhost:8080/ping

###
# LOGIN
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "admin1",
  "password": "securepassword123"
}

# {
#   "username": "driver1",
#   "password": "driverpass789"
# }


# {
#   "username": "customer1",
#   "password": "mypassword456"
# }

##################################################################################
### USERS
GET http://localhost:8080/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc1MDQzMDgsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4xIn0.YpIKAlM6wcXbZkAwAgvDJ0NRJga348DasDqSIqMfzzU

###
GET http://localhost:8080/user/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc1MDQzMDgsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4xIn0.YpIKAlM6wcXbZkAwAgvDJ0NRJga348DasDqSIqMfzzU

###
POST  http://localhost:8080/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc1MDQzMDgsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4xIn0.YpIKAlM6wcXbZkAwAgvDJ0NRJga348DasDqSIqMfzzU

{
  
  "username": "admin12aaaa",
  "password": "securepassword123a",
  "full_name": "Administrators One",
  "email": "admian1@exampleaaaaa.com",
  "phone_number": "+5511987654321",
  "role": "driver"
}
###
PUT  http://localhost:8080/user/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc1MDQzMDgsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4xIn0.YpIKAlM6wcXbZkAwAgvDJ0NRJga348DasDqSIqMfzzU

{
  
  "username": "admin12aaaaaaa",
  "password": "12a3",
  "full_name": "Adminaaaistrators One",
  "email": "admian1@exampleaaaaa.com",
  "phone_number": "+5511987654321",
  "role": "driver"
}

###
DELETE  http://localhost:8080/user/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc1MDQzMDgsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4xIn0.YpIKAlM6wcXbZkAwAgvDJ0NRJga348DasDqSIqMfzzU

#############################################################################################

###
# DRIVER
GET http://localhost:8080/driver/trips
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzU1MTI1MTksInJvbGUiOiJkcml2ZXIiLCJ1c2VybmFtZSI6ImRyaXZlcjEifQ.bdZnlc3NSL-PdxW6taTI7RHdUJuR9coSBrncCmCRrgk
###
# COSTUMER
GET http://localhost:8080/customer/plans
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzU1MTI1MTksInJvbGUiOiJkcml2ZXIiLCJ1c2VybmFtZSI6ImRyaXZlcjEifQ.bdZnlc3NSL-PdxW6taTI7RHdUJuR9coSBrncCmCRrgk


###
# GET ALL DATAS
GET http://localhost:8080/admin/alldata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc1MDQ0MjcsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4xIn0.5_UnTIoWWny4GMoNMFwqdy0_lFi5J1ivdEiPADQ5EZw