version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment: # todo: change all this to envvars
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=your_user
      - DB_PASSWORD=your_password
      - DB_NAME=toorme
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: toorme
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
